version: "3.9"
    
services:

  db:
    image: mysql:5.7
    container_name: database
    command: '--default_authentication_plugin=mysql_native_password'
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} #Environment variables in .env file.
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # Added if you don't need phpmyadmin.
    ports:
    - 3306:3306
    
  wordpress:
    
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "8080:80"
    volumes:
      - ./wordpress_data:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    depends_on:
      - db
      
  # Add the service phpMyAdmin to access and view the database.
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   depends_on:
  #     - db
  #   restart: always
  #   ports:
  #     - 3306:80
  #   environment:
  #     PMA_HOST: db
  #     MYSQL_ROOT_PASSWORT: ${MYSQL_ROOT_PASSWORD}

volumes:
  db_data: {}
  wordpress_data: {}